name: my_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  fl_chart: ^0.69.0
  intl: ^0.18.0
  http: ^0.13.4
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/hiroyuki.png
    - assets/images/avatar1.png

    - assets/images/avatar2.png
    - assets/images/avatar3.png
    - assets/images/avatar4.png
  uses-material-design: true
