// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_auth/firebase_auth.dart';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0g2IOvW3YFg8_tyD-Nuw7GPW0iBQy4QQ',
    appId: '1:586639228845:web:25dfa868f01adff6c3eb24',
    messagingSenderId: '586639228845',
    projectId: 'gpt-motivationapp',
    authDomain: 'gpt-motivationapp.firebaseapp.com',
    storageBucket: 'gpt-motivationapp.appspot.com',
    measurementId: 'G-0KJRBN8Y9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_2ywCQJe3BGEDYekTAj6uZpsL1ppRc3Y',
    appId: '1:586639228845:android:c8d0de158e84a3f0c3eb24',
    messagingSenderId: '586639228845',
    projectId: 'gpt-motivationapp',
    storageBucket: 'gpt-motivationapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBef3xSERJ3dIaxSEB73IPJHJuXIEEWQ48',
    appId: '1:586639228845:ios:52931b2d497f6c4fc3eb24',
    messagingSenderId: '586639228845',
    projectId: 'gpt-motivationapp',
    storageBucket: 'gpt-motivationapp.appspot.com',
    iosBundleId: 'com.yuto.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBef3xSERJ3dIaxSEB73IPJHJuXIEEWQ48',
    appId: '1:586639228845:ios:52931b2d497f6c4fc3eb24',
    messagingSenderId: '586639228845',
    projectId: 'gpt-motivationapp',
    storageBucket: 'gpt-motivationapp.appspot.com',
    iosBundleId: 'com.yuto.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0g2IOvW3YFg8_tyD-Nuw7GPW0iBQy4QQ',
    appId: '1:586639228845:web:7ed98ad510a4f6ccc3eb24',
    messagingSenderId: '586639228845',
    projectId: 'gpt-motivationapp',
    authDomain: 'gpt-motivationapp.firebaseapp.com',
    storageBucket: 'gpt-motivationapp.appspot.com',
    measurementId: 'G-WXJ34XHTVQ',
  );
}
